"""
Visualize the Allen--Cahn residual landscape over the parameter plane.

This script reads the residual grid generated by ``Allen-Cahn-Data.py`` and
plots the mean squared residual as a 3D surface over the parameters (a, b).
The surface helps identify low-residual regions and the geometric structure of
the approximation landscape.

Input
-----
allen_cahn_residual_grid.csv
    CSV file with columns: a, b, residual.

Output
------
allen_cahn_residual_landscape.png
    High-resolution 3D surface plot of the residual landscape.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Load the residual grid computed for the Allen--Cahn trial-function family.
df = pd.read_csv("allen_cahn_residual_grid.csv")

# Convert the long-format table into a matrix suitable for surface plotting.
pivot = df.pivot(
    index="a",
    columns="b",
    values="residual"
)

# Meshgrid coordinates for the parameter plane.
A, B = np.meshgrid(
    pivot.columns.values,
    pivot.index.values
)

# Residual height values on the parameter grid.
Z = pivot.values

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection="3d")

# Draw the residual surface. Low regions correspond to better approximations.
surf = ax.plot_surface(
    A,
    B,
    Z,
    cmap="viridis",
    linewidth=0,
    antialiased=True
)

ax.set_xlabel(r"$b$")
ax.set_ylabel(r"$a$")
ax.set_zlabel("Residual")

# Set the viewing angle to make the geometry of the residual valley visible.
ax.view_init(30, 230)

plt.tight_layout()
plt.savefig(
    "allen_cahn_residual_landscape.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()
