"""
Estimate the number of connected components in Allen--Cahn approximation regimes.

For a sequence of residual thresholds, this script forms the sublevel set

    M_tau = {(a, b) : residual(a, b) <= tau}

and applies DBSCAN to estimate how many connected components appear in the
parameter plane. The resulting curve provides a simple stability diagnostic for
low-residual approximation regimes as the threshold varies.

Input
-----
allen_cahn_residual_grid.csv
    CSV file with columns: a, b, residual.

Output
------
allen_cahn_stability.png
    Plot of the estimated number of connected components versus threshold tau.
"""

import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt


# Load the residual grid generated by the data script.
df = pd.read_csv("allen_cahn_residual_grid.csv")

# Use thresholds from the 1st to the 30th residual percentiles.
taus = np.percentile(
    df["residual"],
    np.arange(1, 31)
)

components = []

for tau in taus:
    # Residual sublevel set at the current threshold.
    M = df[df["residual"] <= tau]

    # Very small point clouds are not reliable for clustering.
    if len(M) < 5:
        components.append(0)
        continue

    # Coordinates in the two-dimensional parameter plane.
    X = M[["a", "b"]].values

    # DBSCAN groups nearby parameter values into connected components.
    # The eps value should be interpreted relative to the spacing of the parameter grid.
    labels = DBSCAN(
        eps=0.01,
        min_samples=5
    ).fit_predict(X)

    # Label -1 denotes DBSCAN noise and is not counted as a component.
    ncomp = len(
        set(labels)
        - {-1}
    )

    components.append(ncomp)

plt.figure(figsize=(7, 5))
plt.plot(
    taus,
    components,
    marker="o"
)

plt.xlabel(r"$	au$")
plt.ylabel("Connected Components")
plt.title("Stability of Approximation Regimes")

plt.tight_layout()
plt.savefig(
    "allen_cahn_stability.png",
    dpi=300
)

plt.show()
