"""
Visualize the Fisher--KPP residual landscape as a 3D surface.

This script reads the residual grid generated by `Fisher--KPP-Data.py` and
constructs a surface plot over the parameter plane (c, a). The vertical axis
represents the mean squared residual of the Fisher--KPP equation for each trial
function. Low regions of the surface indicate parameter values that better
approximate the PDE.

Input
-----
fisher_kpp_equilibrium_residual_grid.csv
    CSV file with columns: c, a, residual.

Output
------
fisher_kpp_equilibrium_landscape.png
    High-resolution 3D visualization of the residual landscape.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Load the residual grid computed by the data-generation script.
df = pd.read_csv("fisher_kpp_equilibrium_residual_grid.csv")


# Convert the long-format table into a matrix suitable for surface plotting.
pivot = df.pivot(
    index="c",
    columns="a",
    values="residual"
)


# Build mesh coordinates for the parameter plane.
A, B = np.meshgrid(
    pivot.columns.values,
    pivot.index.values
)

Z = pivot.values


# Create a 3D residual landscape plot.
fig = plt.figure(figsize=(8, 6))

ax = fig.add_subplot(
    111,
    projection="3d"
)

ax.plot_surface(
    A,
    B,
    Z,
    cmap="viridis",
    linewidth=0
)


# Axis convention: horizontal axes correspond to parameters a and c.
ax.set_xlabel(r"$a$")
ax.set_ylabel(r"$c$")
ax.set_zlabel("Residual")


# Set viewing angle for a clearer landscape perspective.
ax.view_init(30, 230)

plt.tight_layout()

plt.savefig(
    "fisher_kpp_equilibrium_landscape.png",
    dpi=300
)

plt.show()
