"""
Estimate the number of connected components in Fisher--KPP approximation regimes.

For a sequence of residual thresholds tau, this script forms the low-residual
set

    M_tau = {(c, a) : residual(c, a) <= tau}

and estimates the number of connected components using DBSCAN clustering in the
parameter plane. The resulting curve describes how the topology of the
approximation regime changes as the threshold increases.

Input
-----
fisher_kpp_equilibrium_residual_grid.csv
    CSV file with columns: c, a, residual.

Output
------
fisher_kpp_equilibrium_stability.png
    Plot of the estimated number of connected components versus residual
    threshold tau.
"""

import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt


# Load the residual grid generated by the data script.
df = pd.read_csv("fisher_kpp_equilibrium_residual_grid.csv")


# Use thresholds from the 1st to the 30th residual percentile.
taus = np.percentile(df["residual"], np.arange(1, 31))
components = []


# Estimate connected components for each low-residual set M_tau.
for tau in taus:
    M = df[df["residual"] <= tau]

    # Very small sets are not reliable for DBSCAN-based component estimation.
    if len(M) < 5:
        components.append(0)
        continue

    # DBSCAN is applied in the two-dimensional parameter plane (c, a).
    X = M[["c", "a"]].values

    labels = DBSCAN(
        eps=0.035,
        min_samples=5
    ).fit_predict(X)

    # Label -1 corresponds to DBSCAN noise and is not counted as a component.
    ncomp = len(set(labels) - {-1})
    components.append(ncomp)


# Plot topological stability as threshold increases.
plt.figure(figsize=(7, 5))

plt.plot(taus, components, marker="o")

plt.xlabel(r"$	au$")
plt.ylabel("Connected Components")
plt.title("Fisher--KPP Stability of Approximation Regimes")

plt.tight_layout()
plt.savefig("fisher_kpp_equilibrium_stability.png", dpi=300)
plt.show()


# Print numerical values for reproducibility and paper/table reporting.
for tau, comp in zip(taus, components):
    print(f"tau={tau:.3e}, components={comp}")
